version: "3.9"

services:
  python:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=lyvr
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - lyvr-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=lyvr
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
volumes:
  lyvr-data:
